use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use ab_glyph::{Font, FontRef, VariableFont};

/// ASCII range the UI renders (matches the old bitmap font's coverage).
const FIRST: u8 = 0x20;
const LAST: u8 = 0x7E;
const COUNT: usize = (LAST - FIRST + 1) as usize;

/// UI faces, sized for a ~1024px-wide framebuffer.
///
/// Weights mirror superintelmarkets.com: 600 for display/headings, 500 for
/// button labels, 400 for body. Sizes are scaled ~0.85 from the site's
/// 1600px-wide layout so the hero still dominates a 1024x768 guest.
struct Style {
    name: &'static str,
    px: f32,
    weight: f32,
}

const STYLES: &[Style] = &[
    Style { name: "HERO", px: 44.0, weight: 600.0 },
    // Setup-assistant step titles.
    Style { name: "TITLE", px: 30.0, weight: 600.0 },
    Style { name: "H2", px: 22.0, weight: 600.0 },
    Style { name: "BRAND", px: 17.0, weight: 600.0 },
    Style { name: "BODY", px: 17.0, weight: 400.0 },
    Style { name: "BTN", px: 15.0, weight: 500.0 },
    Style { name: "SMALL", px: 13.0, weight: 400.0 },
];

/// Vendored default: Inter, SIL OFL 1.1 (see `assets/fonts/OFL.txt`).
///
/// Keeping this in-tree makes the build reproducible on any host and the ISO
/// redistributable. The system fallbacks below are convenience only — SF Pro
/// is not licensed for redistribution, so an ISO built against it must not be
/// published.
const VENDORED_FONT: &str = "../assets/fonts/InterVariable.ttf";

/// Fallbacks if the vendored font is missing. `OS_UI_FONT` overrides both.
/// Inter and SF Pro are variable, so one file yields every weight; the static
/// fallbacks collapse to a single weight.
const FONT_CANDIDATES: &[&str] = &[
    "/System/Library/Fonts/SFNS.ttf",
    "/System/Library/Fonts/HelveticaNeue.ttc",
    "/System/Library/Fonts/Supplemental/Arial.ttf",
];

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    // Font atlas is needed for both the kernel and host-side lib tests.
    println!("cargo:rerun-if-env-changed=OS_UI_FONT");
    let atlas = build_atlas();
    fs::write(out_dir.join("font_atlas.rs"), atlas).expect("write font atlas");

    let target = env::var("TARGET").unwrap_or_default();
    if !target.contains("none") {
        return;
    }

    let arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap();
    let linker = manifest_dir.join(format!("linker-{arch}.ld"));

    println!("cargo:rustc-link-arg=-T{}", linker.display());
    println!("cargo:rerun-if-changed={}", linker.display());
}

fn find_font() -> (PathBuf, Vec<u8>) {
    if let Ok(p) = env::var("OS_UI_FONT") {
        let path = PathBuf::from(&p);
        let data = fs::read(&path).unwrap_or_else(|e| panic!("OS_UI_FONT {p}: {e}"));
        return (path, data);
    }
    // Vendored font first, so a clean clone builds identically anywhere.
    let vendored = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join(VENDORED_FONT);
    if let Ok(data) = fs::read(&vendored) {
        return (vendored, data);
    }
    for cand in FONT_CANDIDATES {
        let path = Path::new(cand);
        if let Ok(data) = fs::read(path) {
            println!(
                "cargo:warning=vendored {VENDORED_FONT} missing; fell back to {cand}. \
                 The resulting ISO may embed a font you cannot redistribute."
            );
            return (path.to_path_buf(), data);
        }
    }
    panic!(
        "no UI font found; expected {} or set OS_UI_FONT to a .ttf/.ttc (also tried {})",
        vendored.display(),
        FONT_CANDIDATES.join(", ")
    );
}

fn build_atlas() -> String {
    let (path, data) = find_font();
    println!("cargo:rerun-if-changed={}", path.display());

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    let _ = writeln!(out, "// source font: {}\n", path.display());

    let mut faces = Vec::new();
    for style in STYLES {
        faces.push(rasterize(&data, style, &mut out));
    }

    out.push_str("\n/// All UI faces, in declaration order.\n");
    out.push_str("pub static FACES: &[&Face] = &[");
    for name in &faces {
        let _ = write!(out, "&{name}, ");
    }
    out.push_str("];\n");
    out
}

/// Rasterize one style into a packed alpha atlas and emit its Rust consts.
fn rasterize(data: &[u8], style: &Style, out: &mut String) -> String {
    // TTC: face 0 is the family's regular cut; good enough for the fallbacks.
    let mut font = FontRef::try_from_slice_and_index(data, 0).expect("parse font");
    // No-op on static fonts, which simply keep their built-in weight.
    font.set_variation(b"wght", style.weight);

    let scaled = font.as_scaled(style.px);
    use ab_glyph::ScaleFont as _;

    let ascent = scaled.ascent();
    let descent = scaled.descent();
    let line_gap = scaled.line_gap();

    let mut bitmap: Vec<u8> = Vec::new();
    let mut metrics = Vec::with_capacity(COUNT);

    for code in FIRST..=LAST {
        let ch = code as char;
        let glyph_id = font.glyph_id(ch);
        // Advance in 1/64 px so fractional widths and negative tracking
        // accumulate without drift across a whole string.
        let adv64 = (scaled.h_advance(glyph_id) * 64.0).round() as i32;

        let glyph = glyph_id.with_scale(style.px);
        let (w, h, bx, by, off) = match font.outline_glyph(glyph) {
            Some(outlined) => {
                let bounds = outlined.px_bounds();
                let w = bounds.width().ceil() as usize;
                let h = bounds.height().ceil() as usize;
                let off = bitmap.len();
                bitmap.resize(off + w * h, 0);
                outlined.draw(|gx, gy, cov| {
                    let (gx, gy) = (gx as usize, gy as usize);
                    if gx < w && gy < h {
                        // Coverage 0..1 -> 8-bit alpha.
                        bitmap[off + gy * w + gx] = (cov * 255.0 + 0.5).min(255.0) as u8;
                    }
                });
                (w, h, bounds.min.x.round() as i32, bounds.min.y.round() as i32, off)
            }
            // Space and other blank glyphs carry advance only.
            None => (0, 0, 0, 0, bitmap.len()),
        };
        metrics.push((w, h, bx, by, adv64, off));
    }

    let n = style.name;
    let _ = writeln!(out, "pub static {n}_BITMAP: [u8; {}] = [", bitmap.len());
    for chunk in bitmap.chunks(32) {
        out.push(' ');
        for b in chunk {
            let _ = write!(out, "{b},");
        }
        out.push('\n');
    }
    out.push_str("];\n");

    let _ = writeln!(out, "pub static {n}_GLYPHS: [Glyph; {COUNT}] = [");
    for (w, h, bx, by, adv64, off) in &metrics {
        let _ = writeln!(
            out,
            "  Glyph {{ w: {w}, h: {h}, bx: {bx}, by: {by}, adv64: {adv64}, off: {off} }},"
        );
    }
    out.push_str("];\n");

    let face = format!("{n}_FACE");
    let _ = writeln!(
        out,
        "pub static {face}: Face = Face {{ glyphs: &{n}_GLYPHS, bitmap: &{n}_BITMAP, \
         ascent: {}, descent: {}, line: {}, px: {} }};\n",
        ascent.round() as i32,
        descent.round() as i32,
        (ascent - descent + line_gap).round() as i32,
        style.px.round() as i32,
    );
    face
}
