//! Bakes `search/corpus.json` into a static inverted index for `search.rs`.
//!
//! Ported from `kernel/build.rs::build_corpus`. The tokenizer and the index
//! shape are unchanged — only the weights differ: the kernel emitted Q16/Q10
//! fixed point because it never enables the FPU, and this crate has one, so
//! the same quantities are emitted as `f64`.
//!
//! The bake stays at build time rather than moving to a runtime JSON load so
//! that the vocabulary is still a sorted static table the query path can
//! binary-search, and so os-core needs no runtime dependency at all.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let corpus = build_corpus(&manifest_dir);
    fs::write(out_dir.join("corpus.rs"), corpus).expect("write corpus index");
    println!("cargo:rerun-if-changed=build.rs");
}

/// Tokenizer shared with the runtime scorer — must match `search::tokenize`
/// exactly, or a query term cannot find its own vocabulary entry.
fn fold_tok(text: &str) -> Vec<String> {
    text.to_lowercase()
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|w| w.len() >= 2)
        .map(|w| w.to_string())
        .collect()
}

fn build_corpus(manifest_dir: &Path) -> String {
    use std::collections::BTreeMap;

    let path = manifest_dir.join("../search/corpus.json");
    println!("cargo:rerun-if-changed={}", path.display());
    let raw =
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("corpus {}: {e}", path.display()));
    let val: serde_json::Value = serde_json::from_str(&raw).expect("corpus json");
    let docs = val["docs"].as_array().cloned().unwrap_or_default();

    let mut out = String::new();
    out.push_str("// @generated by core/build.rs from search/corpus.json — do not edit.\n");

    // Per-doc tokens: the title counts double, mirroring the host scorer.
    let mut doc_tokens: Vec<Vec<String>> = Vec::new();
    for d in &docs {
        let t = d["t"].as_str().unwrap_or("");
        let b = d["b"].as_str().unwrap_or("");
        let mut toks = fold_tok(t);
        toks.extend(fold_tok(t));
        toks.extend(fold_tok(b));
        doc_tokens.push(toks);
    }

    let n = docs.len();
    let _ = writeln!(out, "pub const N_DOCS: usize = {n};");
    out.push_str("pub static DOCS: [Doc; N_DOCS] = [\n");
    for (i, d) in docs.iter().enumerate() {
        let esc = |k: &str| -> String {
            d[k].as_str()
                .unwrap_or("")
                .replace('\\', "\\\\")
                .replace('"', "\\\"")
        };
        let pr = d["pr"].as_f64().unwrap_or(0.0).clamp(0.0, 1.0);
        let _ = writeln!(
            out,
            "  Doc {{ title: \"{}\", cat: \"{}\", url: \"{}\", pr: {pr:?}, n_tokens: {} }},",
            esc("t"),
            esc("c"),
            esc("u"),
            doc_tokens[i].len().max(1)
        );
    }
    out.push_str("];\n");

    // term -> doc -> raw term frequency
    let mut index: BTreeMap<String, BTreeMap<usize, u32>> = BTreeMap::new();
    for (i, toks) in doc_tokens.iter().enumerate() {
        for t in toks {
            *index.entry(t.clone()).or_default().entry(i).or_insert(0) += 1;
        }
    }

    let mut vocab = String::new();
    let mut postings = String::new();
    let mut n_post = 0usize;
    let mut n_vocab = 0usize;
    for (term, docs_for_term) in &index {
        let df = docs_for_term.len() as f64;
        // idf = ln((N+1)/(df+1)) + 1.
        let idf = ((n as f64 + 1.0) / (df + 1.0)).ln() + 1.0;
        let start = n_post;
        for (doc, tf) in docs_for_term {
            // tf normalised by document length.
            let tfn = (*tf as f64) / (doc_tokens[*doc].len().max(1) as f64);
            let _ = writeln!(postings, "  Posting {{ doc: {doc}, tf: {tfn:?} }},");
            n_post += 1;
        }
        let _ = writeln!(
            vocab,
            "  Term {{ word: \"{term}\", idf: {idf:?}, start: {start}, len: {} }},",
            docs_for_term.len()
        );
        n_vocab += 1;
    }

    let _ = writeln!(out, "pub const N_TERMS: usize = {n_vocab};");
    let _ = writeln!(out, "pub const N_POSTINGS: usize = {n_post};");
    // Sorted by BTreeMap, so the runtime can binary-search.
    let _ = writeln!(out, "pub static TERMS: [Term; N_TERMS] = [\n{vocab}];");
    let _ = writeln!(
        out,
        "pub static POSTINGS: [Posting; N_POSTINGS] = [\n{postings}];"
    );
    out
}
